steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'generate']
  - name: adamharrison/firebase-cli
    args: ['deploy', '--project=fir-static-website-d6299', '--only=hosting']
