steps:
  - name: adamharrison/firebase-cli
    entrypoint: ./create-app.sh
#  - name: node
#    entrypoint: npm
#    args: ['install']
#  - name: node
#    entrypoint: npm
#    args: ['run', 'generate']
#  - name: adamharrison/firebase-cli
#    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']


## after app:create need to catch APP-ID
## then firebase apps:sdkconfig -o appconfig WEB APP-ID
## writes config appconfig file
## need to feed into nuxt.config.js
