steps:
  - name: 'adamharrison/binxly-utils'
    entrypoint: npm
    args: ['install']
  - name: 'adamharrison/binxly-utils'
    entrypoint: npm
    args: ['run', 'generate']
#  - name: 'adamharrison/binxly-utils'
#    entrypoint: 'gsutil'
#    args: ['mb', '-l', 'europe-west2', 'gs://www.binxly.net']
  - name: 'adamharrison/binxly-utils'
    entrypoint: 'gsutil'
    args: ['rsync', '-R', 'dist', 'gs://test.binxly.net']
  - name: 'adamharrison/binxly-utils'
    entrypoint: 'gsutil'
    args: ['iam', 'ch', 'allUsers:objectViewer', 'gs://test.binxly.net']
  - name: 'adamharrison/binxly-utils'
    entrypoint: 'gsutil'
    args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://test.binxly.net']

#  gsutil acl ch -u AllUsers:R gs://example-bucket/example-object
## Setup new CNAME with command line (?)
#  gcloud beta dns --project=$PROJECT_ID record-sets transaction add c.storage.googleapis.com. --name=test.binxly.net. --ttl=300 --type=CNAME --zone=binxly-public-zone-main


## Check DNS commands
#  dig +trace binxly.net
#  dig -t ns binxly.net +short
#  curl -vvv http://test.binxly.net
#  nslookup binxly.net
#  whois binxly.net


# config for build and deploy to firebase

#  - name: node
#    entrypoint: npm
#    args: ['install']
#  - name: node
#    entrypoint: npm
#    args: ['run', 'generate']
#  - name: adamharrison/firebase-cli
#    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']


# trial config for dynamic firebase deploy

#  - name: adamharrison/firebase-cli
#    entrypoint: 'bash'
#    args: ['/create-app.sh', '$BUILD_ID']

## after app:create need to catch APP-ID
## then firebase apps:sdkconfig -o appconfig WEB APP-ID
## writes config appconfig file
## need to feed into nuxt.config.js
