steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args: ['mb', '-l', 'europe-west2', 'gs://www.test.binxly.net']

#  - name: node
#    entrypoint: npm
#    args: ['install']
#  - name: node
#    entrypoint: npm
#    args: ['run', 'generate']
#  - name: adamharrison/firebase-cli
#    args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']


# trial config for dynamic firebase deploy

#  - name: adamharrison/firebase-cli
#    entrypoint: 'bash'
#    args: ['/create-app.sh', '$BUILD_ID']

## after app:create need to catch APP-ID
## then firebase apps:sdkconfig -o appconfig WEB APP-ID
## writes config appconfig file
## need to feed into nuxt.config.js
