steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'generate']
  - name: adamharrison/firebase-cli
    args: ['deploy', '--project=lithe-transport-294511', '--only=hosting']
